# Generated by Django 4.1.1 on 2023-02-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
